-- Tabla principal de ofertas
create table public.deals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Datos del producto
  title text not null,
  marketing_title text, -- Título generado por IA
  marketing_description text, -- Copy generado por IA
  description text,
  
  -- Precios
  price decimal(10,2) not null,
  original_price decimal(10,2),
  discount integer, -- Porcentaje calculado
  
  -- Metadatos
  category text not null, -- 'camping', 'trekking', etc.
  image_url text not null,
  url text not null, -- Enlace original
  affiliate_url text, -- Enlace monetizado
  
  -- Estado
  is_active boolean default true,
  rating decimal(3,1) default 4.5,
  review_count integer default 0
);

-- Habilitar Row Level Security (RLS) para seguridad
alter table public.deals enable row level security;

-- Política: Cualquiera puede LEER (Public Read)
create policy "Public Read"
on public.deals
for select
to public
using (true);

-- Política: Solo servicio (con Service Role Key) puede ESCRIBIR
-- (Supabase permite escritura con Service Role por defecto, esto es explícito para usuarios auth)
create policy "Service Write"
on public.deals
for insert
to service_role
with check (true);
